import subprocess
import sys

for module in ["requests", "bs4", "pyfiglet"]:
    try:
        __import__(module)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", module])

import requests
import json
import time
import threading
import re
import os
from bs4 import BeautifulSoup
import pyfiglet
import random 

CAU_CHUI_1 = [
"Sua de",
"Le de",
"Ngu v",
"Co di",
"lgbt xuất trận eii", 
"Le ei",
"Cham v",
"Co de",
"nhạt nhòe v", 
"Cui v",
"tao là bá chủ thiên hạ đấy", 
"=)))))",
"Nhìn mặt mày là thấy 2 chữ phèn ngu😗",
"Đã nghèo đã phèn đã ngu đã dốt mà đòi hơn ai",
"Bản thân mình không làm được cho mình thì làm được cho ai",
"Sống như 1 con chó ngu dốt như lũ phèn ói chợ búa cầm dao múa kiếm",
"Mau ei",
"Cn cho",
"thấy anh nhây bá k", 
"Cha mày chuyên hành lũ đú mà", 
"Cam a",
"thằng sucvat dân tộc miên hay sao mà đen thế", 
"ơ ơ ơ sao em lại hăng ", 
"R nun",
"dân war 2024 hăng ròi kìa ae",
"Cn thú cầm cái phím tắt ôm trong tuyệt vọng hả", 
"Keng cai",
"Ot a",
"Cay cú anh trong lòng mà không làm đc gì🤔🌶❗", 
"Nhìn mặt mày như con tinh tinh đầu thai chuyển kiếp thành con người v🤣", 
"Keng cai",
"Sua le:))",
"Nhìn con dị hợm quá vậy?",
"Con kiếp trước chắc sống phế lắm nhỉ",
"Qua kiếp này làm lại từ đầu mà sao ngu quá v", 
"mạnh mẽ tí đi nà", 
"Tk não vô sinh ngu ngục quỳ lạy bố đê Kiếm ngôn nào sát thương tí dc k", 
"Oc oi",
"M ôm hận ah đến kiếp sau hả🤨", 
"Cn cho",
"Gần quin rồi ráng thêm sí nữa đi", 
"Le dc k",
"Hay bị cha mày bón cho 1 kí hành dô mõm nên không dám sủa nữa", 
"Ngu a",
"Đú sao lại được hả cn ngồi ôm phím gõ dăm ba mấy cái ngôn xưa lắc xưa lơ", 
"Nhanh ti",
"Tk não vô sinh ngu ngục quỳ lạy bố đê kkk", 
"Xng nun",
"ngôn dell có sát thương à", 
"Log jz",
"Ai cứu mày được quả này",
"Cầu cứu lẹ đi🤣",
"Cha hóng nãy giờ nè🤣",
"Nhai a",
"Lgbt bày binh bố trận dồn cha hả🤪❗",
  "Dồn ngu mà cũng đòi dồn❗🦋",
"Camm ha", 
"THANG DOT TU CHI V THOI A? :))", 
"Loan vey",
"nào mày mới bằng được cái móng chân tao á", 
"Chill cai",
"thằng đầu đinh đâu rồi", 
"Dis con m/e may a. May an khong ngoi roi qua, het viec lam nen di chui phai khong? Neu may deo co viec gi lam thi may dat m/e may di ra ngoai duong voi may, xong 2 m/e con tui may lot do nhau ra ma d/j/t nhau giua duong cho do nhan roi. Ngay xua tao deo co viec gi lam nen tao phai hay di qua nha m/e may de ru ba lam tro do kiem tien song qua ngay day. Ve hoi nha hoi m/e may xem có phai nhu the khong nha ",
"Tao nhanh vcl",
"May sao",
"Sao cho cầu cứu mà cầu cứu xog sao kh ai dám dô giúp ht vậy", 
"Len di",
"Cn di",
"úi úi cay cay cay 😜😜😜🤟🤟", 
"Cn me may",
"Le me v", 
"cố gắng mà để win tao nhe",
"tao bất bại mà thằng ngu",
"ẳng hăng vào đi chứ mày ẳng gì mà nhạt nhẽo thế",
"mạnh mẽ lên xem nào",
"kém cỏi thế thằng mồ côi",
"phản kháng êi sao đứng yên chịu trận vậy",
"Oc cho",
"anh ttho mày bá sàn mà🤪👈👈", 
"Cay a", 
"tao trùm ln rồi còn gì mà cãi nữa", 
"cha ttho bắn hét sọt con già m mà 😜😜🔫", 
"Thk c",
"thằng bất tài vô dụng sủa mạnh lên đi", 
"Dui v",
"123 sua",
"Sủa hăng hái lên chứ yếu kém quá cha mày hăng không nổi😉!",
"Gõ phím tắt để làm nét ai xem",
"Mày đi cầu cứu ai hả!?",
"Tao đố đứa nào dám dô cứu mày đấy",
"Đã ngu còn hay tạo nét",
"Cha mày tới là lũ ngu cũm pải dè chừng",
"Đã ngu còn đú thì phế mẹ đi",
"Cha đấng mxh mà🤔!",
"Cưng ganh tị với anh hả?",
"Cưng hăng hái với ai?",
"Sao con đuối rồi hả?",
"Chỉ được vậy thôi hả!",
"Còn chiêu nào không tung ra đi",
"Chứ thấy mấy cái chiêu trò phèn của mày đi trong ruột mày từ 7 kiếp r ",
"Hom nay chị nghe được cái tin đồn thất thoái tuyệt tình con d/i~ bà già mày không có tiền mua băng vệ sinh tới cái thời khắc đỉnh điểm rụng dâu tới tháng t/ử cung âm đạo con d/i/m/e mày chảy huyết canh m/á/u tươi ra như cái sông mê công phân bố chia ngã ra mấy tỉnh đồng bằng sông cửu long nhìn tùm lum sẵn tiện để tao khui cái chuyện năm xưa gia môn mày bán nước theo giặc luôn một thể nha con phản quốc mày nhìn cái thân thể điêu hoa chet đứng trong khói lửa nhả ra cái ngữ nào cũng không đủ khả năng thấm da thấm thịt chị mày không mà lên đây gõ túi bụi rồi thiên hạ nhị vào đánh giá chả ra cái hệ thống gì nghe tin chị gõ cái sớ ngôn thất kinh bát quái như kinh thánh của chúa phân bố cho nhân tộc nghe xong chân tay bủn rủn run như chưa tháo máy run từ cái bàn quan con bóng chos bà già mày cố trụ cho tới ngày tao thuê cái xe rồng đưa tang chôn cất cho con m/e mày làm đám tang nha🤪🤪",
"Bot a",
"May treo a?",
"May ma",
"Con thú ngu dốt bị cha mày hành cho đầu óc quay cuồng r à", 
"Cai thk ngu",
"Cay mếu máo sao khóc rồi", 
"Lam jz",
"Não tàn đến mức phải đi xin tha hả?",
"Não mày chứa toàn cứt của con dog nhà mày à",
"Sao mày không hăng hái nữa",
"Hay rớt rồi hả",
"Sao câm nín rồi 😑",
"Sủa hăng hái máu chiến lên nào",
"Yếu kém v con thú đú ngu êy",
"Sủa sao cho nghe lọt lỗ tai",
"Cha tới nè nhú lên diện kiến cha lẹ",
"Bame mày quỳ lạy kêu anh xin tha mà",
"Cốt cách như buồi gõ xàm gõ điên",
"Gõ sao lại tụi anh được hả lũ đú ",  
"🤣🤣🤣",
"Cay r",
"Thiên truy ngũ giác gõ ra mấy câu như xói xỉa vào trong mặt thiên hạ đang xem mày diễn tuồng lan và điệp đem mấy câu từ này lên với chốn quan tọa như lời tâm thư gửi tới gia môn như lời cảnh báo d/i/m/e mày sắp bị chính đức con mang tên kim ke đẻ ra chôn sống đào nguyệt đạo nhồi nhét vào anh mày thấy mà ngán ngẫm cái cách gắn ghép chữ nghĩa không rành mạch của con mặt l/o/n mày bị anh giải ra pháp trường xử tử công khai cầm cái nồng súng được tỉa bắn sởn da đầu làm cho dân chúng bàng hoàng vì trước mặt anh đây là con yêu quái đang làm xằm làm bậy nguy danh oai phong lẫm liệt khoáy đảo chốn càng khôn cái trình gà mờ tịt ra mà cũng dám lên đây tỉ thí so tài cao thấp khiến tâm trí nó hạn hẹp gõ như đang ói mửa vào chén cơm manh áo của con d/i/m/e nó đi xin ăn la lết cái thân thể đi cầu may vận rủi để về nuôi nó cho nó thất học xấu hổ với bạn bè ở nhà làm nhục nhã gia môn ngũ hầu phong tọa lâu la như mày anh đây vung cao thanh gươm c/h/ặ/t lìa thân thể thành hai khúc thịt tươi dục xuống dưới bên cảng nhà rồng hiện cái thân thể điêu tàn chet điêu đứng của mày lên nhờ sự cứu giúp tương trợ của quan văn tướng võ triều đình mà cũng hô hào tên tuổi khoe mẽ chiến tích bị gõ cho bục đầu cái bao biện lí do như đứa trẻ lên ba đi học bị bạo lục học đường tự kỉ bỏ học đi bán vé số mưu sinh kiếm sống làm cái nghề dơ bẩn của thiên hạ khinh thiên tứ hải💢‼️",
"Cha mày tới là lũ ngu cũm pải rén mà thôi", 
"Hăng lên xíu được không dọ",
"cn thu hoang yeu duoi thieu oxi nen khong cam hung de hang ha cn bede gia trai di lua tinh nguoi dung duong🙄🙄👈", 
"Nín hết rồi hả sao không hăng như ban đầu đê",
"Cưng hăng hái 1 cách bất thường à🤣",
  "Cay cú anh trong lòng mà không làm đc gì🤔🌶",
  "Sao mày ngu như 🐮 v",
  "Cay cay cay cha rồi🤣",
  "Ai cho mày cay cha hả🤣",
  "Cay chừa phần người ta với🤣",
  "Cay ht phần thiên hạ là sao dị🤨",
  "Sao mà xạo l/o/n",
  "Dân va 2024 à",
  "Chỉ có vậy thôi sao",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi🥺?",
  "bị chửi nên không phản kháng à😀?",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
"d/j/t con d/i/m/e mày trơ cái con ngươi tròng trắng đen lẫn lộn khi bị tao cầm đôi đũa sắc chọt duyệt giác mạc thấy cái con l/o/n ốm nhôm ốm nhách bị cha mẹ gia đình bạn bẹ ruồng bỏ cô lập từ năm này sang năm nọ bỏ đói từ ngày này qua tháng nọ không khác con yêu nghiệt ba đầu bảy đuôi thảm sát gia môn kill ba mẹ mày khi ổng bả cố gượng gồng cái sức bình sinh yếu kém của thân già bệnh tật nghèo nàn không tiền chạy căn bệnh ung thư giai đoạn cuối mà còn đi xuống cái cống rãnh móc ổ bánh mì từ bãi rác đem cho mày ăn cứu đói sống qua ngày mà mày lên đây bàn chuyện thiên hạ cái thứ sucvat như mày bị tao hành hình nhốt vào lãnh cung chung với bọn đầu trâu mặt ngựa cho tan thành mây khói vạn kiếp bất phục",
"Can ot a",
"Hieu lun",
"Mày bt anh là chuyên trừng trị những thể loại như m kh", 
"Ngung a", 
"Thấy cha là xách giò chạy hả", 
"Nghi luc len",
"Sua jz",
"Ngồi nhây tới đêm trăng tròn nè=))", 
"=)))))",
"Ai cay v",
"sao thế tk não phẳng",
"Âm binh kìa ae🤣  ",
"Ê thằng đầu đinh  ",
"Ê chx tới tết  ",
"hăng lên con",
"sao m yếu ớt v🌶",
"CÂM LÀ CẢ NHÀ M DIE DƯỚI 💀TAY CHA😣∋⓪①②③( =ノωヽ=)◉‿◉🐮🐮", 
":))))",
"Sao do con",
"Thk beo",
"Lgbt a",
"Lgbt xuất trận hả hay sao 🤔?", 
"Lo lo:))",
"Ei cn bede",
"Mày ngưng là má mày đột tử tới",
"Thú đú như mày làm cha bùn cười quá ",
"Khi nào có trình đú với anh nha",
"Sao chậm quá vậy?😂",
"Sủa hăng hái mạnh mẽ lên",
"Cốt cách thiên nga tâm hồn quỷ dữ 😈",
"Thân tàn ma dại",
"may thi tuoi l/o/n an duoc tao ne on l/o/n la sao ma trau la sao ma hay ma can ngon ngu roi con d/i~ can ngon ngu hay may liet ngon ngu ha con d/i cai l/o/n ba gia con d/i/m/e nha may con d/i~ am binh am khi am l/o/n dai duong dai bang no con ia vo hong l/o/n may nua do thang l/o/n trinh ngu gioi cai sua ngu chuong tai gai mat thi tao dí😏😏",
"Con dốt bame mày đẻ ra con quái thai",
"Si ma",
"Oc c",
"Sao v mặt căng v cay cha rồi hả 🤨🌶?", 
"Le eii",
"Mày bị cha hành mà:3",
"Cha cấm mày bịa chuyện nha🤔",
"Cha quin mà cn thú êy🤪",
"Hóng quin đc cha lắm hỏ🤪",
"Ê cn quái thú🤪",
"Mày là cn quái thú giữa rừng xanh mà🤪",
"phai chang nam xua anh may tram xi mang vao lo am dao nhu dong phong nha cua con d/i/m/e may lai roi, thi nam nay tao da khong met moi trung tri con quai thai lai chos ton tai o duong gian ma khong biet trung thanh voi chu roi vo day but toc nay gio tu phia xoay 180 do cung khong ran ra duoc cau nao hay ho ra tro lan quan may cau nhu l/o/n nha ngon nghe ung thu tai bieng vay ma cung bat chap sua", 
"Sao bị cha chửi mà tha hóa lun r🤪",
"Thk bem",
"Không được cay anh quá mà làm liều nghe chưa!", 
"Dc k v",
"Đuối r thì kêu cha cha tha cho", 
"Đừng có lên mạng xã hội tạo nét mà bị anh hành là mếu máo đi cầu cứu ngay", 
"K ma", 
"Cn ga", 
"Thứ súc sinh muốn tiến hóa thành người",
"Skill cai",
"Cha là chúa thánh🐒🎶 đên đây để bịt mõm mấy tk anh hùng:)))", 
"Oc cho:))",
"Cui v",
"ê wavy giả bộ ngừng đi",
"Gõ ngôn lặp đi lặp lại ngôn 1 màu thì đừng gõ",
"Thứ yêu nghiệt xuống hạn nhân sanh",
"Thk culi",
"Cai thk heo",
"Le boa",
"Ngu v boa",
"Alo con còn sống kh đó", 
"Hay bị hành quá nên sinh ra hoang tưởng", 
"Sua dien eii",
"Chậm chạp như rùa bò v", 
"Sao em",
"chung sinh binh dang, sinhvat ha dang do ban cam len tieng vi deo co quyen ly do hay y kien‼️🤪👈", 
"Ngồi xuống cha giảng đạo cho nghe nè",
"Nghèo bần hèn bị cha mày đứng trên đạp đầu lũ đú chúng mày cha đi lên ",
"Cay mếu máo cha mà chả làm được gì hả",
"Không được quay qua méc mẹ nghe chưa",
"Đã ngu còn thích thể hiện hả thk nhóc",
"Khi nào đủ trình r so với anh nghe chưa",
"Thân phận nghèo hèn đú ai xem",
"Đã ngu còn thích sỉ diện",
"Chó ngoan cục cưng hãy về với chủ đừng cắn bậy",
"Sống sang lên cho nết thanh tịnh",
"Sống dơ sống hèn muôn đời bết",
"Còn sống thì nhú lên đú tiếp cho tụi anh chiêm ngưỡng",
"Tàn tạ từ nhân cách đến não bộ",
"Sống cho cuộc đời có tâm và có tầm",
"Ngu thì đừng phán vs ai nhé cn chó ghẻ ",
"Nghe 1 thời giảng sanh của cha mà tích đức",
"Khi nào con có đủ tầm ảnh hưởng lên đứng với cha",
"thag sucvat bat hieu liem l/o/n me may khen ngon truoc su chung kien cua thag cha may ma oc ngu🤪👈", 
"Thương cho con thú cay anh mà không làm được gì", 
"may la sucsinh phevat top1 MXH ma xao l/o/n boa hoa ngon ngu sucvat cho con d/i/m/e may coi ha em🤨", 
"can canh con mo coi can ba~ liem giai cha de xin tha mang cho c/o/n/d/i/m/e nó nè cac em🤣🤣", 
":)))",
"kho than con chos oc c/a/c cay anh den tan xuong tuy ma dam mom l/o/n dao ly", 
"sucsinh du trinh liem cut anh de song qua ngay ma tuong minh la thiem kim dai tieu thu ha🤨‼️", 
"oc du ma tuong minh la dang MXH gap hw ttho la ngay tan may toi ne em", 
"sucvat kem coi~ ma ao tuong ban than la ba chu son lam hom nay cha ttho chui cho may thoat khoi cai ao mong xam l/o/n do ne🤪❓", 
"ngu si dot nat ma xao l/o/n la con d/i/m/e may cung khong help noi cai mang chos cua may dau em🤪🤪👈", 
" hom nay troi dep mat me cha se bao dung nhe nhang ma ban an tu cho ca nha may die 1 cach the tham🔪🤪👈", 
"bu tinh cha le thi may ra cai mang chos cua may duoc giu lai ma khong bi xuoc", 
"cha ttho dang san ma‼️🤪👈", 
"can canh con oc du meu mao vi bi cha chui ma bat luc khong the phan khang🤣🤣", 
"Mày tưởng mày đang đóng vai ng đẹp và quái vật hả🤪",
"Thoát ra khỏi cái mộng tưởng đó đi nhóc🤪",
"may con cai gi moi hon khong em cu dien mai 1 vai anh may chan loi con c/a/c roi ne cn thu eii🤨‼️", 
" con d/i~ oc bo` bi cha chui ma chi bic cam lang  trong tuyet vong🙄🙄👈", 
"may yeu duoi kem coi toi noi khong bic nhay la gi a thag bem💢🤨❓", 
"can cha day may cach nhay khong do con chos bede nha` la??? ", 
"cha ttho ba san cmnr ke ca con d/i oc ngu bi anh chui con khong dam phan khang", 
"con d/i/m/e may quy lay van xin anh du dieu de tha cho mang chos may ma em", 
"sucvat khong bic dieu bao hieu bame may ma con dam loan luan gia dinh ha thag bat hieu", 
"con d/i/m/e may mang bau 9 thang 10 ngay ma khong ngo con gai m/e may lai de ra con quai thai quai thu bu dai ong hang xom loan luan voi cha ruot... ", 
"khi thuy trieu dang cao cung la luc ca nha may bi anh cam dinh ba tan sat the tham🤪💢", 
"pho nong thon ngon thoi tien su ma dam ngong l/o/n ngua hang cho con d/i/m/e may hui", 
"cn bong nha la bede dau thai chuyen kiep dinh tao net khong may gap cha ttho nen bi chui tet nao khien con bem bi khuyet tat ca doi tan tat tro thanh nguoi thuc vat chi bic om c/a/c nam im 1 cho🤪💢‼️", 
"khuyet tat ngon ngu 4 chi bai liet dau oc chua tinh ma doi so do voi cha ha cn thu hoang🤪🤪",
"hw ttho d/u con d/i/m/e may tet l/o/n ri mau lientuc ma🤪🤪", 
"lu ngu bi cha hanh ha nhu dog giu nha ma sao xao l/o/n dien hai cho anh coi ha❓🤨👈", 
"Sao mấy cn thú đi theo bầy đàn bị cha mày hành tới mức mà pải núp hết rồi dị",
"cn sucvat chos ghe bi anh chui cho tha hoa ma bay dat giay giua xao l/o/n truoc mat cha ttho ha em🤪‼️",
"luc cha xuat tran cung la luc lu oc du ngu boai phai cuoi dau quy lai vi ba khi cua anh qua khung khiep🤣🤣👈", 
"lu bede bai nao dung cay anh qua ma dien loan len can bay nha tr🤪🤣", 
"cn tinh tinh doi lot nhan dan ma tuong minh la phien ban thuong hang sicula hot xoang ha🤣🤣", 
"cn kiki nao tinh trung bi anh chui xuong 18 tang dia nguc khong duoc dau thai chuyen kiep suot doi hau ha dau trau mat ngua nhu no le tinh duc ma", 
"culi chau phi da den nhu cut trau ma dam xao sua tam bay la con d/i/m/e may die the tham", 
"lu ngu bi anh be co tran yem vong hon vao cai quan lot cua con gai m/e may ma", 
"sua diên di ma sua hang len moi vui😘",
"may ma ngung mot giay la con d/i/m/e may ba tat duong tho a", 
"vao 1 hom bong con d/i/m/e nha may die thi luc do cha lam ba chu san m/e r :))",
"do tao qua ba chu thiet ra may cung ngu như chos  =))) ",
"hw ttho trùm đấng mxh ai làm lại anh đâu😁",
"thag sucvat não vô sinh ngu ngục quỳ lạy cha đê =))) ", 
"mày lấy x/a/c chuột nhét vào cái l/o/n m/e mày à??? ", 
" thag rẩu l/o/n chưa ra đời mà đã chơi với cha à😏😏💢", 
"m/e mày còn đang đợi tao đút c/a/c vào l/o/n đó 🤣🤣👈", 
"ME MAY BI ANH KHAU LON NEN PHAI DI DAI BANG LO Đ/Í/T DUNG K???",
"m/e mày bị anh móc l/o/n bắn tung tóe kìa thag bất hiếu", 
"cn d/i/m/e mày bị cha d/j/t tới tấp mà thag sucvat??? ",
"BÁ CHỦ SÀN WAR ĐẤNG MXH GỌI TÊN TTHO🤪🤪",  
"tao lấy l/ô/n/g chim cha l/ô/n/g l/o/n m/e mày cho chos nhai", 
"tao còn cho thag cha mày liếm đ/ý/t đầy c/ứ/t của tao nữa đó💢🤣👈", 
"không được cay cha nha cha mày nói thế thôi chứ lỡ khi mày cay cha thật thì phải làm sao hả đú🤣🤣", 
"cái d/j/t con m/e mày thg ngu ơi mày sủa tao xem di nào , con thú ăn c/ứ/t mxh:))", 
"đáp ngôn nhanh hơn tý đc k thag oc ngu xuẩn🌬 🤢🤢", 
"mày nhắm chơi lại tao không mà dám đú vậy con sucsinh phevat :)))",
"thag ngu khong co nao thay phai gan nao bo` thay the🤣🤣", 
"cai cn khong co dia vi bang 1 cn sucvat nua🤪💢",
"cha may go cho may nguyen 1 tran lan dai hai🤣‼️", 
"go cho may sieu thoat qua the gioi ben kia🤣🤣🤣", 
"Bị cha mày hành nhiều quá nên sính ra hoa tưởng hả 🤨?!",
"Con sống ngu mà con hay tạo nét quá v cn thú ngu êy",
"Nhai hoai",
"ròi lun cn quasi thú bị anh sỉ nhục cn m/e nó ròi kaka🤣",
  "sỉ nhục như cn sucsinh bậc thấp k có địa vị trên cõi đời🤣",
"Đã ngu còn thích tỏ ra mình có trình hả cn thú ngu êy", 
"cn bào thai trong ống nghiệm cũng bic mếu à🤣", 
"cha may hoa than thanh hac bach vo thuong cha may bat hon d/i/m/e may xuong chau diem vuong ne 😜😜🔫",
"sua hang hai len sao di du da du don xao l/o/n tap du mxh"
"dung bi anh chui nhieu qua ma tu ai nhay lau tu tu nhe", 
"con diem pho ma bi cha may cam cai cay cha bon cau cha cha` nat l/o/n may ne",
"sao con du ma con xao l/o/n ha cn thu ngu ey",
"cam la cha may goi hon may nhu goi do"
"con so ho la xao lon bia chuyen ai xem", 
" Thang sucvat oc c/a/c bat hieu giet thang cha d/i m/e may ma🤣🤣❓", 
"nao may bi chen tinh trung cua thang cha may trong ha?",
"con d/i/m/e may bat luc vi bi tao chui ma chi biet cam lang:)))", 
"thang bede ao c/a/c doi can va cai ket:)))",
"con d/i/m/e cua may them cut tao du lam:)))", 
" phevat bi cha chui sang c/a/c deo dam care:)))",
"cham vay sao cuu duoc con d/i/m/e may nhanh len di chu:)))",
"ê nói thật luon thua thì thua đi ai cấm đâu",
"noi voi may moi hon nhap c/u vao l/o/n m/e may",
"mày sủa chill như cách cn chos nhà mày sủa đê🤣",
"bj cha ttho mày đọa đày xuống diêm la địa phủ😗",
  "để đầu thai chuyển kiếp thành sucvat đú war🤣",
"Con may bi t hanh chet len chet xuong ma oc du ao mxh🤣‼️👈",
"may dang tap tanh danh van tung cau tung chu 1 cho tao nghe a tk bede",
"may oc ro ma may xao l/o/n voi cha a con chos ngu", 
"sao may bat luc de anh hanh ha v ha con chos ngu=))) ", 
" bi anh chui den noi con d/i/m/e may dut mong chet di song lai khong kip a",
"khoi co xao l/o/n voi tao dau tk tam hon chos dai may bi anh chui den noi khong kip dau thai a:)))", 
"phevat bai liet 4 chi bi hw ttho duc lientuc khien cn oc ngu bi tham ca l/o/n🤪🤪", 
"d/i/t m/e may len sua di ne m so anh hay gi😏💢", 
"gap hw ttho la lu ngu chi bic vay duoi cui dau quy lay van xin😏😏💢", 
"cha cam dinh ba dam loi cuong hong d/i/m/e may lien", 
"d/i/t con m/e lu du het thoi len day xung danh voi ai??? ", 
" sao may song mat day qua vay bame may kho ma may con luoi‼️❓", 
"the hien minh co trinh di con chos ngu nguc eii💢💢", 
"khi nao co trinh roi do voi anh chu khong trinh ma sua hang ghe ta🤨❓", 
"Khi nào đủ trình r so với anh nghe chưa",
"Thân phận nghèo hèn đú ai xem ",
"d/i/m/e may toi thang xit nuoc mau kinh cho thk cha may uong",
"sua do cha may cam cai choi nhet vo l/o/n may ne",
"Cn thú mại d/â/m bán d/â/m mà như bán trinh hoa hậu v🤣",
"cái thứ con người mà não còn không có mà đòi đọ với ai🤣",
"con d/i~ ngu bi cha chui khong ngoc dau len duoc🤣🤣", 
"thag ngu du bi cha chui khong cho ngoc dau len duoc🤣💢", 
"con chos ngu nguc the hien trinh bi anh sut nat c/a/c🤣🤣", 
"con d/i/m/e may bi may loan luan d/j/t rung cai l/o/n ma🤣‼️", 
"c/a/c chua moc long ma doi du nay du kia🤣🤣👈", 
"nhin thag oc dai ngu dang du bot nhin bua vay🤣❓", 
"eii vo tran duy hung tao thay con d/i/m/e may dung dau duong ngay cho nga tu a😳😳", 
"cha bat bai moi san dau ma thag dai chos 🤣🤣🤖👈👈👈", 
"cụ tổ may co loan luan voi em gai may khong? 🌐", 
"cha chat dai thag cha may cho con d/i/m/e may an ma em🤣🤣👈", 
"khong lam gi duoc anh nen cay a thag nao cho??? ", 
" tao vua d/j/t m/e may vua hat nhu Quang Tho, d/j/t xong roi cam co le tao go mo boong boong, cam co le tao go mo coong coong. ☺",
"may gap tao trung dai len cuong hong roi a🤨💢‼️",
"sao may tham lon cam tao lau nuoc mat k???", 
"con kiki dai tham liem chan anh le =)))🤣🤣‼️",
" con d/i~ cai cun voi cha bi bem rot oc ma 🤣🤣👈",
"cn tinh tinh đội lót nhân dân hại dân lành🤪🔪‼️",
"ai cho mày sủa tao cho mày sủa chưa con d/i~ ngu? ?? ", 
"bị tao chọc cay hơn con chos luôn mà bày đặt xạo l/o/n =)))",
"m/e may bi tao d/j/t dot quy ngoai nha nghi kia dem hom ra vot xac con d/i/m/e may nha🥺🥺💢",
"dem 2 cai may voi con d/i/m/e may luon nha thg bel kkk",
"kham chui vo buom con d/i/m/e no chan keo nup trong a:))))", 
"hinh anh cn bem bi cha dap:)) ui con gie rach‼️🤪👈",
"sao may no dut con c/a/c vao cai l/o/n het tinh dich cua con m/e may vay🤨❓", 
"anh la ac quy phi phai ma, anh cam shot gun ban nat dau con d/i/m/e may luon do tin khong🤣🤣🔫", 
"ban mat l/o/n cua may dinh day cut chos kia lau dum cai di con d/i~ nhin ban vai🤢🤮", 
"thang ngu bi cha chui deo ngoc dau len noi, ngoc len la cha dap nam xuong lai tao thay may cay anh lam roi thang bat hieu", 
"buon cha thang cha voi con d/i/m/e may co 1 dua con beo hinh beo dang nhu con quai thai=))", 
" con d/i/m/e may ngong qua vua ngong vua ngu-))nao nhoi nhet cut hay gi ma deo thong noi cau tao noi?",
"may tin cha may cat con c/a/c thang cha may xeo hang con d/i/m/e may vi cai toi deo biet day con đe con an noi ham ho mat day voi nguoi lon khong?🤗😃",
"Nhìn mày gõ như đống tro tàn cốt mã nhà mày để lại cho mày vậy á",
"gap hw ttho la ngay tan may toi vi luc do cung la luc cha tu hinh may ngay tren dai hanh quyet🤪🤪👈", 
"sao may tham lon cam tao lau nuoc mat k???", 
"mày húp huyết tử cung cn d/i/m/e mày khen béo à sucsinh🤣💢", 
"con kiki dai tham liem chan anh le =)))🤣🤣‼️",
" con d/i~ cai cun voi cha bi bem rot oc ma 🤣🤣👈",
"cn tinh tinh đội lót nhân dân hại dân lành🤪🔪‼️",
"con mo coi bi hw ttho d/j/t rach tu cung ri mau lientuc khong ngung🤣🤣🤣", 
"cn sucvat loan luan gia dinh siet co cha ruot bang day ao nguc😳‼️❓",
"dong cai ngu dao nhai hom nay gap cha la cha go kinh phat xam hoi cho may troi tru dat diet tuyet chung ca pha nha may ne con ngu nguc🤣🤣‼️",
"am binh net re rach tam xich tuong nen xich luon cai l/o/n khai kham cua may ma😳🤣",
"cn sucsinh dia vi chi nhu cn quai thai ha dang ma doi so do voi cha🤣🤣",
"cn sucvat bị HW TTHO hành hạ k bằng 1 con nô lẹ campuchia😳💢", 
"hãy cảm ơn trời vì hôm nay mày dc hw ttho dzs1tg ban án tử nha cn thu🤪🤪👈",
"sát thương tí đi dc kh 😜",
"nhìn mày phèn phèn bẩn bẩn",
"speed x1000 cho anh xem", 
"sao m nghịch tử vậy tk não cao su",
"Cay chua",
"con bede cay dai kieu", 
"Cay ro:))",
"cố lên kkkk gần bại r đó", 
"R x",
"Cha mày tới đâu là lũ đú phải dè chừng",
"Đã ngu còn thích tỏ ra mình có trình hả cn thú ngu êy",
"Bởi vì mày làm gì có trình ?",
"Khi nào có trình r đọ với anh chứ trình không có mà sủa hăng ghê ta", 
"Ot nun",
"Oc nun",
"Duoi a",
"Thk ngu?",
"Sao rồi ổn kh",
"Hay ổn lòi lìa😴😳",
"Nhìn mặt m là bt không ổn r😳",
"Cn tinh tinh bị cha đọa đày😁",
"s v thag ngu?",  
"não m chứa cứt haaa",
"con chos oc c/a/c hăng lẹ lên🙄", 
"úi úi alo aloo", 
"bú c/a/c anh lẹ nè em", 
"ơ ơ s v tròi, dc bú c/a/c hw mà chê???", 
"con d/i~ m/e mày ngu buoi v em", 
"lu~ oc c/a/c sồn anh lẹ lẹ coi🙄👈", 
"im re v chèn ơi phế đến v đó hả😑?",
"Nín hết rồi hả sao không hăng như ban đầu đê", 
"Cha mày tới là lũ ngu cũm pải rén mà thôi", 
"May sua",
"Co le",
"tới sáng đi cục cưng của cha", 
"Alo:)?",
"SUC VAT TINH TRUNG FAKE", 
"lên bem cha đê🤣🤔", 
"Win nha",
"Tao win ma",
"ttho xin win trận này😂🤨", 
"An hoi a",
"Oki tiep ei",
"Le xiu",
"con sugar daddy :)))", 
"CHA CHO M CAM CHUA👉🤣", 
"Cham v",
"th xong nước mắt cả sấu à=))", 
"nhìn mặt m tởm gớm", 
"mặt toàn mụn với rỗ kìa=))", 
"trông mà phát ghê", 
"miệng hôi sữa", 
"vắt mũi ch sạch mà đú war à", 
"Mau ei",
"Cn ga nay",
"xem m trụ đc bao lâu:))", 
"Du a",
"Cn cho cay",
"Met chua",
"Sao mấy cn thú đi theo bầy đàn bị cha mày hành tới mức mà pải núp hết rồi dị", 
"Câm rồi à chán thế",
"Mày nín r hả",
"Sao nín r vậy",
"Hay bị mẹ gank rồi",
"Yếu kém quá cn thú ơi",
"Hay đuối rồi jar",
"Đuối r thì kêu cha cha tha cho",
"Sao pải cuốn cuồng lên thế🤣",
"Ai làm gì mà mếu r v",
"Cay cú kh làm đc gì à",
"Mếu máo rõ mà rồi sao nữa ht ngôn à ",
"=)))",
"Tao nhanh vcl",
"May cham vc:))",
"Thk beo nay",
"Khi nào con có đủ tầm ảnh hưởng lên đứng với cha",
"Sợ tao lắm đk", 
"cha ttho bá đạo vcl mà con=))", 
"Sao v",
"THANG OC LON MO COI=))", 
"Mau di o",
"Sua cai",
"Ngung me may a",
"Thk dot",
"t cân cả dòng họ m mà:))", 
"Win nhoa",
"nhây sao lại anh", 
"úi con sucvat háng thâm😜😜", 
"Cam cay",
"Ớt cãy",
"Đời quá chán nên Tao chả ngán đứa nào, xông vô và tao sẽ cho mày đi ôtô ra Nghĩa Địa =))", 
"Ngu ngu",
"ăn hại phát biểu lẹ đê 🤣🤣", 
"Sua di cn",
"cave tỉnh lẽ phát biểu:))", 
"Lofi cai",
"CHA ĐẤNG MXH MÀ🤣🤣", 
"Cn cho con",
"=)))",
"2 con bede không phản kháng được à😋", 
"2 con bede sợ anh rồi:))🙃", 
"chạy về mách mom à 2 con bede😗?", 
"Lam j v",
"Met a em",
"CHA WIN NỮA RỒI À =))", 
"Thoi ah win nha",
"LẠI WIN RỒI HEHEH", 
"lần sau gặp cha ttho thì xin tha đi🤣", 
"Cam an hoi",
"An hoi may die",
"Nghe ch",
"Bai nha cn",
"KAKA TINH TRUNG KHUYET TAT", 
"👉🤣🤣",
"Sao v",
"Choi a",
"Cayyy",
"Đừng cay cú cha mà hóa rồ lên làm nét", 
"sài adr 2m đòi khè ai v tr 😜😜👍", 
"úi cn bẻm bị anh chà đạp", 
"Sua le",
"Ngu a",
"nè thang chos, ra nghe bo noi nay, ngay xua m/e con mat trinh non cung la vi bo day, roi m/e con dai ia ra con cung la do bo day, roi m/e may sinh ra may nhu mot thang quai thu, moi lan cho bu tao phai dut cu vao trong mom may vi con m/e may khong co vu", 
"Cn ngu",
"Trận này anh win rõ mà sao cưng chối ăng ẳng thế", 
"Sua di?",
"Xom di",
"nghèo k có nghi lực à:))", 
":)))",
"Gõ cho mày tá hỏa tâm tinh🤪", 
"R nun",
"Ot nun",
"lại phải win nữa à🙄🙄", 
"Win mà🤣",
"cha mãi win nè👅", 
"ớ ớ ớ ttho là hw mà 😜😜🔫",
"Lũ đú hết thời lên đây xưng danh với ai",
"thẩm du cái lồn má m lên🤣👈",
"con đĩ cãi cùn",
"địt bà nội sư gia nhà m =))",
"úi úi",
"nhanh lên con chó lồn khai khắm=))",
"sao con đĩ mẹ mày gà vậy",
"địt lồn mẹ mày",
"dập cặc thằng cha mày liền",
"Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
"Con thú đú",
"lòi lồn chiến sĩ rồi à",
"sao không mạnh mẽ lên",
"khép lép vậy",
"sợ hãi rồi à",
"Lẹ lên con điếm thúi",
"con đĩ mồ côi ăn hôi",
"thế nào rồi",
"sợ anh mày chưa",
"anh mày bá sàn mà",
"sao m chối hoài",
"chối là con má m die",
"ngu thì ngu vừa thôi=))",
"không t đâm chết thằng cha mày",
"óc chó dữ",
"lồn mẹ mày",
"điếm thúi ơi=))",
"đừng rớt nhây nhó:3",
"thấy sao rùi:3",
"Bede sủa tiếng nghe choiw",
"Cặc Cặc Cặc",
"Lồn Lồn Lồn",
"=))",
"Thấy anh nhây bá ko",
"quá bá mà",
"sao lại anh được",
"khép đuôi xin tha đê",
"Rủa đĩ má m die",
"Ngồi nhây tới đêm trăng tròn nè=))",
"Nhây sao lại anh",
"Bóng sida",
"bede dập cu ơi=))",
"nhắm chửi lại anh không=))",
"lẹ lên con đĩ",
"điếm thúi ăn hôi ơi:))",
"Lên xem còn tài cán gì không nào",
"Sao mà xạo lồn",
"Chỉ có vậy thôi sao",
"mày làm được gì không😤",
"hay chỉ biết phản kháng🤭=))",
"tk cu bé phản kháng di😏?",
"con đĩ cave luôn khảng phán đi🥺?",
"bị chửi nên không phản kháng à😀?",
"2 con bede không phản kháng được à😋",
"2 con bede sợ anh rồi:))🙃",
"chạy về mách mẹ à 2 con bede😗?",
"chạy về trốn dô cái lồn mẹ mày đi😍?",
"1 đứa bú lồn mẹ😎?",
"1 đứa bú cu cha😎?",
"bất hiếu cmnr 😜👈",
"mày làm gì để anh sợ đi:))🤣?",
"mày có tý sát thương nào ko😂?",
"con đĩ mẹ mày ăn cứt cố đi🤣?",
"mày sợ anh à con chó ăn cứt:))?",
"anh win cmnr clm🤣",
"lũ cave cay cha cmnr😑",
"Cha mày tới đâu là lũ đú phải dè chừng",
"Đã ngu còn thik tỏ ra mình có trình hả cn thú ngu êy",
"Khóc r hả thương vậy",
"Thương cho con thú cay anh mà không làm được gì",
"Sao cho cầu cứu mà cầu cứu xog sao kh ai dám dô giúp ht vậy",
"Sống chi bần hèn quá v",
"Sao con đú mà con xạo lồn hả cn thú ngu êy",
"Cha mày chuyên hành lũ đú mà",
"Con sủa hăng máu lên ",
"Câm là cha mày gọi hồn mày như gọi đò",
"Con sơ hở là xạo lồn bịa chuyện ai xem",
"Nhìn con dị hợm quá vậy?",
"Con kiếp trước chắc sống phế lắm nhỉ",
"Qua kiếp này làm lại từ đầu mà sao ngu quá v",
"Cn thú cầm cái phím tắt ôm trong tuyệt vọng hả",
"Đú sao lại được hả cn ngồi ôm phím gõ dăm ba mấy cái ngôn xưa lắc xưa lơ ",
"Ai cứu mày được quả này",
"Cầu cứu lẹ đi🤣",
"Cha hóng nãy giờ nè🤣",
"Mẹ mày làm con chó canh cửa cho nhà t mà🤣",
"Mẹ m bị xe cán lòi não kìa",
"Ra nhặt về đi",
"Mẹ m bị chó nhà anh some mà",
"Cha ruột m là chó mà 😜",
"Thú ngu bị cha sút về hành hạ mẹ ruột kìa",
"Mẹ m bị anh treo cổ mà😜",
"Chó ngu bị cha nhét cứt đến die mà🤣🤣🤣",
"Khẩu phần ăn của mẹ m là cứt mà😜",
"Thú ngu cay kìa=}",
"Óc cặc cay anh đến độ trứng dái sắp bay ra ngoài r kìa=)))",
"sồn hăng lên em",
"sao m yếu v",
"cố tí nữa",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em eii",
"cố gắng tí eii",
"k đc à",
"con eii cố de",
"sao m câm kìa",
"gà j",
"phãn kháng đi con chó",
"cha bá sàn cmnr tk sủa mạnh lên dc k chó",
"tk ớt cay kiểu",
"đúng mà",
"m hoản loạn khi gặp cha à",
"mày còn gì khác k",
"gà mà m xạo lồn vs cha m à",
"tk súc sinh",
"mếu à",
"đầu đình tứ phủ",
"bị a đá lên đầu lên cổ",
"va lẹ eii",
"sao kìa",
"từ bỏ r à",
"nhìn a",
"phập lồn con gái mẹ m",
"m bất lực",
"kh lm j dc anh",
"sao mày bất lực để anh hành hạ vậy hả con chó ngu =))))",
"cay lắm phải kh",
"đúng k",
"tk não chó",
"m liếm lồn dê khen béo à",
"tk óc heo",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"tk óc heo",
"mày nghĩ mày làm t cay đc à",
"m chỉ bt ngồi",
"tao đang hành m mà",
"rênh rỉ gào thét",
"trong vô vọng à",
"tk giả gái sủa hăng lên",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"sồn mạnh lên",
"chửi như m đéo ai nghe",
"coi tụi nó dồn ngu kìa",
"ae ơiii",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"nó treo à ae 🤣",
"yếu đến thế à",
"cay lắm à :))",
"nhạt nhoè v à",
"ko cảm hứng để hăng à :)))",
"xạo lồn à :)))",
"khóc đk :)))",
"cave tỉnh lẽ phát biểu:))",
"ra tín hiệu đê :)))",
"SOS con dái đú 🤣🤣🤢",
"ớ ớ ớ :)))",
"chó ăn cứt :)))",
"chó đú sàn 👌🐶",
"ỉa ra máu r à :)))",
"nghèo k có nghi lực à:))",
"phản kháng đê :))) t win à",
"kkk",
"m chết r à :)))",
"m nghèo mà em 😏🤣",
"m thèm cứt t mà:))",
"đĩ mẹ m ngu mà👉🤣",
"m cay tao mà :))",
"con óc cứt thối🤢🤢",
"con đĩ mặt chim🤪🤪",
"ôm hận à 🤨",
"con đĩ nhà núi :)))",
"bede bóng lộ =))",
"cn đĩ mẹ mày",
"tao từ hình mẹ m mà :))",
"tk phế vật ăn hại😏🤘",
"đú đởn hả con :))",
"m sao dọ",
"sủa nè ",
"123 sủa😏",
"lẹ nè ",
"alo alo hú hú ",
"th cầm thú",
"m s dạ ",
"m sợ mẹ hả ",
"lên đi mẹ ko giết cha má m đâu mà 😏",
"hù :))",
"bất ổn hở",
"s đó ",
"m rớt kìa th gà🤪",
"t cấm m chối nhen",
"chối t giết cha má m nè:)))",
"hăng xíu lẹ kaka🤢",
"th đần ",
"lên mẹ biểu",
"k lên t tuyệt chủng m nhen cn thú",
"m thích đú ko dạ🤨",
"ko rep = t win nhen ",
"cấm chạy nhen",
"m mau ",
"lên đây ơ ơ ",
"th ngu ê",
"s á lên đây mẹ sút m chết",
"m khóc à 👉🤣",
"sủa liên tục ơ🤣🤣",
"cầu cứu lũ đú à ",
"sục dái nó xem à",
"dái thâm v?",
"chậm v cn culi🤣🤣👌",
"hoảng loạn à",
"bất ổn à 🤮🤮",
"run à",
"chạy à ",
"đuối à ",
"bại chưa 👉😏",
"sủa mau🙄🙄👈",
"mạnh dạn lên ",
"nhanh t cho cơ hội cứu má m nè",
"cấm mách mẹ",
"ảo war hở :))",
"dồn ko ",
"đua nè lên sàn t chấp😏👌",
"th chợ búa m sao v",
"th đầu buồi mặt chó😢🫵🏻👈🏻",
"cấm hoảng loạn",
"lại phải win nữa à🙄🙄",
"sủa điên lên cho mẹ?  ",
"mày ngưng là con đĩ mẹ mày chết?  ",
"cay tao lòi dái hả😏  ",
"não chó cay à?🤣  ",
"sao mày thảm dị=)))  ",
"mẹ mày bị tao địt rách màn trinh mà🤪  ",
"mẹ mày bị tao dã vào lồn=)))  ",
"địt mẹ mày sướng tê con cặc=)))  ",
"huhu nhìn mày như con cặc=)))  ",
"mày loạn luân bà già hả=)))  ",
"mẹ mày bị tao địt rên ư ử=)))  ",
"địt mẹ mày sảng khoái quá đi😛  ",
"tao địt mẹ mày nát lồn mà=)))  ",
"Kkk",
"chạy về trốn dô cái lồn mẹ mày đi😍?",
"bất hiếu cmnr 😜👈",
"mày làm gì để anh sợ đi:))🤣?",
"mày có tý sát thương nào ko😂?",
"con đĩ mẹ mày ăn cứt cố đi🤣?",
"mày sợ anh à con chó ăn cứt:))?",
"anh win cmnr clm🤣",
"lũ cave cay cha cmnr😑",
"Cha mày tới đâu là lũ đú phải dè chừng",
"Đã ngu còn thik tỏ ra mình có trình hả cn thú ngu êy",
"Khóc r hả thương vậy",
"Thương cho con thú cay anh mà không làm được gì",
"Sao cho cầu cứu mà cầu cứu xog sao kh ai dám dô giúp ht vậy",
"Sống chi bần hèn quá v",
"Sao con đú mà con xạo lồn hả cn thú ngu êy",
"Cha mày chuyên hành lũ đú mà",
"Con sủa hăng máu lên ",
"Câm là cha mày gọi hồn mày như gọi đò",
"Con sơ hở là xạo lồn bịa chuyện ai xem",
"Nhìn con dị hợm quá vậy?",
"Con kiếp trước chắc sống phế lắm nhỉ",
"Qua kiếp này làm lại từ đầu mà sao ngu quá v",
"Cn thú cầm cái phím tắt ôm trong tuyệt vọng hả",
"Đú sao lại được hả cn ngồi ôm phím gõ dăm ba mấy cái ngôn xưa lắc xưa lơ ",
"Ai cứu mày được quả này",
"Cầu cứu lẹ đi🤣",
"Cha hóng nãy giờ nè🤣",
"Mẹ mày làm con chó canh cửa cho nhà t mà🤣",
"Mẹ m bị xe cán lòi não kìa",
"Ra nhặt về đi",
"Mẹ m bị chó nhà anh some mà",
"Cha ruột m là chó mà 😜",
"Thú ngu bị cha sút về hành hạ mẹ ruột kìa",
"Mẹ m bị anh treo cổ mà😜",
"Chó ngu bị cha nhét cứt đến die mà🤣🤣🤣",
"Khẩu phần ăn của mẹ m là cứt mà😜",
"Thú ngu cay kìa=}",
"Óc cặc cay anh đến độ trứng dái sắp bay ra ngoài r kìa=)))",
"sồn hăng lên em",
"sao m yếu v",
"cố tí nữa",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em eii",
"cố gắng tí eii",
"k đc à",
"con eii cố de",
"sao m câm kìa",
"gà j",
"phãn kháng đi con chó",
"cha bá sàn cmnr tk sủa mạnh lên dc k chó",
"tk ớt cay kiểu",
"đúng mà",
"m hoản loạn khi gặp cha à",
"mày còn gì khác k",
"gà mà m xạo lồn vs cha m à",
"tk súc sinh",
"mếu à",
"đầu đình tứ phủ",
"bị a đá lên đầu lên cổ",
"va lẹ eii",
"sao kìa",
"từ bỏ r à",
"nhìn a",
"phập lồn con gái mẹ m",
"m bất lực",
"kh lm j dc anh",
"sao mày bất lực để anh hành hạ vậy hả con chó ngu =))))",
"cay lắm phải kh",
"đúng k",
"tk não chó",
"m liếm lồn dê khen béo à",
"tk óc heo",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"tk óc heo",
"mày nghĩ mày làm t cay đc à",
"m chỉ bt ngồi",
"tao đang hành m mà",
"rênh rỉ gào thét",
"trong vô vọng à",
"tk giả gái sủa hăng lên",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"sồn mạnh lên",
"chửi như m đéo ai nghe",
"coi tụi nó dồn ngu kìa",
"ae ơiii",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"nó treo à ae 🤣",
"yếu đến thế à",
"cay lắm à :))",
"nhạt nhoè v à",
"ko cảm hứng để hăng à :)))",
"xạo lồn à :)))",
"khóc đk :)))",
"cave tỉnh lẽ phát biểu:))",
"ra tín hiệu đê :)))",
"SOS con dái đú 🤣🤣🤢",
"ớ ớ ớ :)))",
"chó ăn cứt :)))",
"chó đú sàn 👌🐶",
"ỉa ra máu r à :)))",
"nghèo k có nghi lực à:))",
"phản kháng đê :))) t win à",
"kkk",
"m chết r à :)))",
"m nghèo mà em 😏🤣",
"m thèm cứt t mà:))",
"đĩ mẹ m ngu mà👉🤣",
"m cay tao mà :))",
"con óc cứt thối🤢🤢",
"con đĩ mặt chim🤪🤪",
"ôm hận à 🤨",
"con đĩ nhà núi :)))",
"bede bóng lộ =))",
"cn đĩ mẹ mày",
"tao từ hình mẹ m mà :))",
"tk phế vật ăn hại😏🤘",
"đú đởn hả con :))",
"m sao dọ",
"sủa nè ",
"123 sủa😏",
"lẹ nè ",
"alo alo hú hú ",
"th cầm thú",
"m s dạ ",
"m sợ mẹ hả ",
"lên đi mẹ ko giết cha má m đâu mà 😏",
"hù :))",
"bất ổn hở",
"s đó ",
"m rớt kìa th gà🤪",
"t cấm m chối nhen",
"chối t giết cha má m nè:)))",
"hăng xíu lẹ kaka🤢",
"th đần ",
"lên mẹ biểu",
"k lên t tuyệt chủng m nhen cn thú",
"m thích đú ko dạ🤨",
"ko rep = t win nhen ",
"cấm chạy nhen",
"m mau ",
"lên đây ơ ơ ",
"th ngu ê",
"s á lên đây mẹ sút m chết",
"m khóc à 👉🤣",
"sủa liên tục ơ🤣🤣",
"cầu cứu lũ đú à ",
"sục dái nó xem à",
"dái thâm v?",
"chậm v cn culi🤣🤣👌",
"hoảng loạn à",
"bất ổn à 🤮🤮",
"run à",
"chạy à ",
"đuối à ",
"bại chưa 👉😏",
"sủa mau🙄🙄👈",
"mạnh dạn lên ",
"nhanh t cho cơ hội cứu má m nè",
"cấm mách mẹ",
"ảo war hở :))",
"dồn ko ",
"đua nè lên sàn t chấp😏👌",
"th chợ búa m sao v",
"th đầu buồi mặt chó😢🫵🏻👈🏻",
"cấm hoảng loạn",
"lại phải win nữa à🙄🙄",
"sủa điên lên cho mẹ?  ",
"mày ngưng là con đĩ mẹ mày chết?  ",
"cay tao lòi dái hả😏  ",
"não chó cay à?🤣  ",
"sao mày thảm dị=)))  ",
"mẹ mày bị tao địt rách màn trinh mà🤪  ",
"mẹ mày bị tao dã vào lồn=)))  ",
"địt mẹ mày sướng tê con cặc=)))  ",
"huhu nhìn mày như con cặc=)))  ",
"mày loạn luân bà già hả=)))  ",
"mẹ mày bị tao địt rên ư ử=)))  ",
"địt mẹ mày sảng khoái quá đi😛  ",
"tao địt mẹ mày nát lồn mà=)))  ",
"Kkk",
"Con đĩ mẹ mày sủa điện loạn đê",
"Hăng lên t xem ",
"Mày ngu rõ mà",
"Chửi tí sát thương đi ",
"Sao mày gà v ",
"Mày ngưng 1 giây là con đĩ mẹ mày chết liền ",
"sao kia", "manh di ma", "kem ak", "sao kia", "son de", "run ak", "thg an hai","cay tao ak", "cay lam ak", "sao roi nhi", "bat luc ak", "lien tuc de", "tiep de m","nhay keo k e", "ga vay e", "hoc lom ak", "ko slow ma","speed de", "hai vai l","m dot ak", "thg oc cut", "chay de", "chat le dei", "co len", "mo coi ak", "cay ak", "ccho cayya ak", "oc cac ak", "chay ak em", "sua mau dei", "sua le dei", "tk dot", "tk oc dai", "sua le de", "manh kg", "manh ma e", "man ma em", "tk dot", "ui mo coi", "sua lej9 dei", "oc loz ak", "tk boai ngu", "son dc kg", "oc trau ak", "le ma em", "hot nhay ma", " tk oc dai", "sua manh kg", "m bi ngu ak", "sua mau kg", "oc trau ak", "speed em", "le nun ma", "tk dot cut", "bi ngu ak", "son de em", "ccho dien", "nhanh vl ma", "tay ma em", "slow ak", "oc boai ak", "tk dot", " bia ngu ak", "sua le nun", "phat bieu le", "tk dot nay", "mo coi me ak", "tk ngu", "sao da", "anh man mak", "cay akk", "sua mauu", "sloww akk", "le em", "nhanh em", "clmkks", "con cho dien", "sua em", "speed ma", "m slow ay", "m slow vl", "anh speed vkl", "le em", "clm ngu ak", "tk ga nay", "con loz", "sua le lun em", "clm dot ak", "keo man cai", "man off mxh de", "kg dam ak", "tk ngu ren", "cay r ak", "cay cmnr", "m cay ro", "nhanh ti", "le len e", "co de", "sap dc r", "co gang em", "bat luc r ak", "ui tk ga", "ga bat luc", "duoi r ak", "moi tay ak", "kakakak", "sua le nun", "chill ma", "bth ma em", "m bat on ak", "anh dg chill", "sua manh em", "kg dc treo nha", "tay vs bo de", "cn boai", "nao cho ak", "clm", "sua mau de", "ga ak m", "slow r ak m", "duoi r ak", "kh nghi ngoi", "lien tuc ma", "lien tuc nun", "chat lien tuc", "le kja m", "sao roi", "dien dai ak", "le len cmm", "so t ak", "clm dot ak", "anh kg bt duoi", "le ma em", "sua de", "tk dot nay", "le me ak", "tk oc bo", "loan phim r ak", "oc cho", "kay roi ak", "le de m", "clm ga l", "man off kg", "kay ak em", "tk oc l", "le len", "lien tuc ma", "slow kia", "oc ak", "cayy r", "muon win ak", "dot s win", "kakakk", "yeu akk may", "nhanh ma", "speed vl ayh nhi", "z ha m", "m dot ak", "m dot ma e", "tk dot kakka", "🤣🤣", "slow v", "le hon de", "lofi lun", "ui ga", "cay rui ak", "lien tuc de", "yeu v ak", "manh hon di", "kg dc ak", "oc cho ak", "sua lien tuc ma", "clm tk dot", "lien tuc nao", "sao roi m", "slow v ak", "ngu ak em", "tk dot dai cho", "liec tuc de m", "Sua lien tuc", "ko dc ak", "clm slow v", "nhanh ti dc kg", "cut tay ak", "tk ngheo", "m te nan ak", "phe ak", "co gang", "sap dc r", "ti nx di m", "speed xiu nx", "sap dc r do", "ga v ak", "sao doa kaka", "m ngu ak", "m dot ro", "tk oc dai", "oc trau ak", "cmm dot the", "man ma m", "manh nun ma", "tk dot slow v", "cay r ak", "sua de m", "lofi ma m", "sua chill v", "tk ga âkkak", "le de m", "Chill z", "sua lien tuc", "m that hoc ak", "m cay ak", "le ti de", "khac nx di", "ko lau ak", "ko sua ak", "soa da", "bt sua kg", "moe may", "sao dot v", "that hoc ak m", "cuoiia kakak", "lien tuc nua de", "le me ak", "son dj m", "tk cho dien", "hang le di m", "cho dien kg son ak", "ko vui r e", "k son chan the", "sua de m", "Alo", "lien tuc ma", "clmm", "tk mo coi", "dot ak m", "anh hot nhay ma", "nhanh ti", "co ti nua m", "co nua", "sap dc roi do", "co len m", "deo dc r ak", "bat luc ak",  "ga v em", "oc c loan luan", "tk cho dien", "son di m", "bat luc ak", "moi tay r ak", "duoi ak m", "ko on r ak", "k nghi ngoi ma", "speed ma m", "k speed dc ak", "oc cho z", "slow lai r ak", "sua lien tuc di", "k rot ma", "con di", "me m", "duoi ak", "le ma m", "r x", "lai victory ak", "victory ak", "victory tk slow ak", "k cay ma", "sao v", "cay ak m", "speed di", "dot ak m", "thg phe", "le lun", "oc cak", "sua dei", "kakâk", "le kg m", "tk dot", "cay r ak", "bat luc ak", "duoi r ak", "son dei", "tk ba do", "chay kg", "son le dei", "con cho", "cho dien cay", "ba m ngu", "clm rot ak", "lien tuc dei", "bo m speed", "speed ma", "kg on r ak", "oc lz ak", "tk ngu", "s duoi r", "nhay ngu ak", "nhay keo kg", "tk oc heo", "bu dai ak", "loan phim ak", "bat luc r ak", "deo laiik ak", "clm sua deii", "lienmienn akk", "chay ak", "le tay di", "suai le", "om han ak", "le m", "hap hoi ak", "thg phe", "que tay ak", "clm ga v", "le dei", "ngu ak", "kg son ak", "slow ak", "bat luc ak", "bat luc hot nhay ak", "m co hot k", "m hot j ay", "hot cut ak", "tk ga", "k speed dc", "doi hot nhay ak", "bo speed vl", "le ma may", "kg son dien a", "lej dei", "clm", "sua lofi e", "kg sua ak", "sao kg sua", "kg lien tuc ak", "rot nx ak", "sao ay nhi", "tk ga", "nhay ngu z", "sua dien loan ak", "co gang di", "co nua dei", "sao r", "bat luc ak m", "tay speed vcl", "man kg e", "man off kg m", "tk dot ngu", "oc cho ak", "cay r ak", "het son ak", "sao slow nx r", "duoi r ha", "moi tay ak", "anh uoc duoi", "anh manh vkl", "suadi em", "ot ak", "cay dien r", "kakak", "anh tay ma", "speed vl ay", "m sao lai", "m slow vc", "chat cham v", "lag ak m", "dap dt ak", "cay cmnr ak", "tk dot", "kg hoc ak", "ngu da", "sao do", "lien tuc di", "kg cham ma", "kakak", "tiep tuc de", "speed kg ays", "kg noi ak", "tk ga", "ga cay", "ot r ak", "so bo ak", "a speed vl", "keo man kg", "thg oc dai", "co nua dei", "sap dc r ay", "anh victory ak", "clm victory r", "victory r ak", "ez ak", "kaka", "lien tuc di", "sua manh", "nhanh kg", "cham ak",
"sua de", "cam a", "hang de", "s da", "sợ à m", "toc do ba", " speed dei" , "cham da ba", "phế a m", "bia a m", "sua đi m", "con ngu", "cay à ba", "m phèn ma", "choi ik m", "dg cau cuu a ba", " chậm à", "anh bá mà m", "sua de","cn mm","sao ay", "sua de","cay a","maude","nhanh de","sao doa","le de","cay a","sao ay","sua di m","cay a","djt me m","con mm","hang de em","moi tay am","duoi aak","duoi ke","clm m","cay t ak","speed m","sua de","gay a","yeu ak","met ak","phe kk","nhanh dei","ga ak","bede ak","sua de","cay ak","nhanh len","cham ak m","sao da","mau di m","sua hang kg","phe ak","sua de","nhanh de ","hang de","mau de","gay a","bede ak","dit mm","dua de","cay vl ak","sua mau de","nhanh len","nhanh kg" ,"sao da","o ke","cham da","t nhanh vvl","lien tuc dei","dua du","toc do de","sua de","le de","cay ak m","sua de m","sua chay di","con cho","ga ak cn","bia a","con cho ngu","soeed di m","dien me r","so ak","so ke","cay","chay ak","gay ke","clm m","akaka","cn mm","chill di","sua du","nhanh m","ga ak","tk cac",

]

CAU_CHUI_2 = [
"sao kia", "manh di ma", "kem ak", "sao kia", "son de", "run ak", "thg an hai","cay tao ak", "cay lam ak", "sao roi nhi", "bat luc ak", "lien tuc de", "tiep de m","nhay keo k e", "ga vay e", "hoc lom ak", "ko slow ma","speed de", "hai vai l","m dot ak", "thg oc cut", "chay de", "chat le dei", "co len", "mo coi ak", "cay ak", "ccho cayya ak", "oc cac ak", "chay ak em", "sua mau dei", "sua le dei", "tk dot", "tk oc dai", "sua le de", "manh kg", "manh ma e", "man ma em", "tk dot", "ui mo coi", "sua lej9 dei", "oc loz ak", "tk boai ngu", "son dc kg", "oc trau ak", "le ma em", "hot nhay ma", " tk oc dai", "sua manh kg", "m bi ngu ak", "sua mau kg", "oc trau ak", "speed em", "le nun ma", "tk dot cut", "bi ngu ak", "son de em", "ccho dien", "nhanh vl ma", "tay ma em", "slow ak", "oc boai ak", "tk dot", " bia ngu ak", "sua le nun", "phat bieu le", "tk dot nay", "mo coi me ak", "tk ngu", "sao da", "anh man mak", "cay akk", "sua mauu", "sloww akk", "le em", "nhanh em", "clmkks", "con cho dien", "sua em", "speed ma", "m slow ay", "m slow vl", "anh speed vkl", "le em", "clm ngu ak", "tk ga nay", "con loz", "sua le lun em", "clm dot ak", "keo man cai", "man off mxh de", "kg dam ak", "tk ngu ren", "cay r ak", "cay cmnr", "m cay ro", "nhanh ti", "le len e", "co de", "sap dc r", "co gang em", "bat luc r ak", "ui tk ga", "ga bat luc", "duoi r ak", "moi tay ak", "kakakak", "sua le nun", "chill ma", "bth ma em", "m bat on ak", "anh dg chill", "sua manh em", "kg dc treo nha", "tay vs bo de", "cn boai", "nao cho ak", "clm", "sua mau de", "ga ak m", "slow r ak m", "duoi r ak", "kh nghi ngoi", "lien tuc ma", "lien tuc nun", "chat lien tuc", "le kja m", "sao roi", "dien dai ak", "le len cmm", "so t ak", "clm dot ak", "anh kg bt duoi", "le ma em", "sua de", "tk dot nay", "le me ak", "tk oc bo", "loan phim r ak", "oc cho", "kay roi ak", "le de m", "clm ga l", "man off kg", "kay ak em", "tk oc l", "le len", "lien tuc ma", "slow kia", "oc ak", "cayy r", "muon win ak", "dot s win", "kakakk", "yeu akk may", "nhanh ma", "speed vl ayh nhi", "z ha m", "m dot ak", "m dot ma e", "tk dot kakka", "🤣🤣", "slow v", "le hon de", "lofi lun", "ui ga", "cay rui ak", "lien tuc de", "yeu v ak", "manh hon di", "kg dc ak", "oc cho ak", "sua lien tuc ma", "clm tk dot", "lien tuc nao", "sao roi m", "slow v ak", "ngu ak em", "tk dot dai cho", "liec tuc de m", "Sua lien tuc", "ko dc ak", "clm slow v", "nhanh ti dc kg", "cut tay ak", "tk ngheo", "m te nan ak", "phe ak", "co gang", "sap dc r", "ti nx di m", "speed xiu nx", "sap dc r do", "ga v ak", "sao doa kaka", "m ngu ak", "m dot ro", "tk oc dai", "oc trau ak", "cmm dot the", "man ma m", "manh nun ma", "tk dot slow v", "cay r ak", "sua de m", "lofi ma m", "sua chill v", "tk ga âkkak", "le de m", "Chill z", "sua lien tuc", "m that hoc ak", "m cay ak", "le ti de", "khac nx di", "ko lau ak", "ko sua ak", "soa da", "bt sua kg", "moe may", "sao dot v", "that hoc ak m", "cuoiia kakak", "lien tuc nua de", "le me ak", "son dj m", "tk cho dien", "hang le di m", "cho dien kg son ak", "ko vui r e", "k son chan the", "sua de m", "Alo", "lien tuc ma", "clmm", "tk mo coi", "dot ak m", "anh hot nhay ma", "nhanh ti", "co ti nua m", "co nua", "sap dc roi do", "co len m", "deo dc r ak", "bat luc ak",  "ga v em", "oc c loan luan", "tk cho dien", "son di m", "bat luc ak", "moi tay r ak", "duoi ak m", "ko on r ak", "k nghi ngoi ma", "speed ma m", "k speed dc ak", "oc cho z", "slow lai r ak", "sua lien tuc di", "k rot ma", "con di", "me m", "duoi ak", "le ma m", "r x", "lai victory ak", "victory ak", "victory tk slow ak", "k cay ma", "sao v", "cay ak m", "speed di", "dot ak m", "thg phe", "le lun", "oc cak", "sua dei", "kakâk", "le kg m", "tk dot", "cay r ak", "bat luc ak", "duoi r ak", "son dei", "tk ba do", "chay kg", "son le dei", "con cho", "cho dien cay", "ba m ngu", "clm rot ak", "lien tuc dei", "bo m speed", "speed ma", "kg on r ak", "oc lz ak", "tk ngu", "s duoi r", "nhay ngu ak", "nhay keo kg", "tk oc heo", "bu dai ak", "loan phim ak", "bat luc r ak", "deo laiik ak", "clm sua deii", "lienmienn akk", "chay ak", "le tay di", "suai le", "om han ak", "le m", "hap hoi ak", "thg phe", "que tay ak", "clm ga v", "le dei", "ngu ak", "kg son ak", "slow ak", "bat luc ak", "bat luc hot nhay ak", "m co hot k", "m hot j ay", "hot cut ak", "tk ga", "k speed dc", "doi hot nhay ak", "bo speed vl", "le ma may", "kg son dien a", "lej dei", "clm", "sua lofi e", "kg sua ak", "sao kg sua", "kg lien tuc ak", "rot nx ak", "sao ay nhi", "tk ga", "nhay ngu z", "sua dien loan ak", "co gang di", "co nua dei", "sao r", "bat luc ak m", "tay speed vcl", "man kg e", "man off kg m", "tk dot ngu", "oc cho ak", "cay r ak", "het son ak", "sao slow nx r", "duoi r ha", "moi tay ak", "anh uoc duoi", "anh manh vkl", "suadi em", "ot ak", "cay dien r", "kakak", "anh tay ma", "speed vl ay", "m sao lai", "m slow vc", "chat cham v", "lag ak m", "dap dt ak", "cay cmnr ak", "tk dot", "kg hoc ak", "ngu da", "sao do", "lien tuc di", "kg cham ma", "kakak", "tiep tuc de", "speed kg ays", "kg noi ak", "tk ga", "ga cay", "ot r ak", "so bo ak", "a speed vl", "keo man kg", "thg oc dai", "co nua dei", "sap dc r ay", "anh victory ak", "clm victory r", "victory r ak", "ez ak", "kaka", "lien tuc di", "sua manh", "nhanh kg", "cham ak",
"sua de", "cam a", "hang de", "s da", "sợ à m", "toc do ba", " speed dei" , "cham da ba", "phế a m", "bia a m", "sua đi m", "con ngu", "cay à ba", "m phèn ma", "choi ik m", "dg cau cuu a ba", " chậm à", "anh bá mà m", "sua de","cn mm","sao ay", "sua de","cay a","maude","nhanh de","sao doa","le de","cay a","sao ay","sua di m","cay a","djt me m","con mm","hang de em","moi tay am","duoi aak","duoi ke","clm m","cay t ak","speed m","sua de","gay a","yeu ak","met ak","phe kk","nhanh dei","ga ak","bede ak","sua de","cay ak","nhanh len","cham ak m","sao da","mau di m","sua hang kg","phe ak","sua de","nhanh de ","hang de","mau de","gay a","bede ak","dit mm","dua de","cay vl ak","sua mau de","nhanh len","nhanh kg" ,"sao da","o ke","cham da","t nhanh vvl","lien tuc dei","dua du","toc do de","sua de","le de","cay ak m","sua de m","sua chay di","con cho","ga ak cn","bia a","con cho ngu","soeed di m","dien me r","so ak","so ke","cay","chay ak","gay ke","clm m","akaka","cn mm","chill di","sua du","nhanh m","ga ak","tk cac",
]

# ===== MÀU =====
trang = "\033[1;37m\033[1m"
xanh_la = "\033[1;32m\033[1m"
xanh_cyan_dam = '\033[1m\033[38;5;51m'
xanhnhat = "\033[1;34m\033[1m" 
do = "\033[1;31m\033[1m\033[1m"
xam = '\033[1;30m\033[1m'
vang = "\033[1;33m\033[1m"
tim = "\033[1;35m\033[1m"

def print_colorful_line(text):
    colors = [
        '\033[94m',
        '\033[96m',
        '\033[97m'
    ]
    reset = '\033[0m'
    result = ''
    for i, char in enumerate(text):
        color = colors[i % len(colors)]
        result += color + char
    return result + reset

def print_colorful_banner(banner_text):
    lines = banner_text.split("\n")
    for line in lines:
        print(print_colorful_line(line))

def print_colorful_box():
    reset = '\033[0m'
    text_lines = [
        "Tool: Gửi tin nhắn Facebook(War)",
    ]
    max_len = max(len(line) for line in text_lines) + 4
    top_bottom = "═" * max_len

    print('\033[96m' + "╔" + top_bottom + "╗" + reset)
    for line in text_lines:
        colorful = print_colorful_line(line)
        padding = max_len - len(line)
        print('\033[94m' + "║  " + colorful + ' ' * (padding - 2) + "║" + reset)
    print('\033[96m' + "╚" + top_bottom + "╝" + reset)

class Messenger:
    def __init__(self, cookie):
        self.cookie = cookie
        self.user_id = self.get_user_id()
        self.fb_dtsg = None
        self.init_params()

    def get_user_id(self):
        try:
            return re.search(r"c_user=(\d+)", self.cookie).group(1)
        except:
            raise Exception("Cookie không hợp lệ")

    def init_params(self):
        headers = {
            'Cookie': self.cookie,
            'User-Agent': 'Mozilla/5.0'
        }
        try:
            for url in ['https://www.facebook.com', 'https://mbasic.facebook.com', 'https://m.facebook.com']:
                response = requests.get(url, headers=headers)
                match = re.search(r'name="fb_dtsg" value="(.*?)"', response.text)
                if match:
                    self.fb_dtsg = match.group(1)
                    return
            raise Exception("Không tìm thấy fb_dtsg")
        except Exception as e:
            raise Exception(f"Lỗi khởi tạo: {str(e)}")

    def send_message(self, recipient_id, message):
        timestamp = int(time.time() * 1000)
        data = {
            'fb_dtsg': self.fb_dtsg,
            '__user': self.user_id,
            'body': message,
            'action_type': 'ma-type:user-generated-message',
            'timestamp': timestamp,
            'offline_threading_id': str(timestamp),
            'message_id': str(timestamp),
            'thread_fbid': recipient_id,
            'source': 'source:chat:web',
            'client': 'mercury'
        }
        headers = {
            'Cookie': self.cookie,
            'User-Agent': 'Mozilla/5.0',
            'Content-Type': 'application/x-www-form-urlencoded'
        }
        try:
            response = requests.post('https://www.facebook.com/messaging/send/', data=data, headers=headers)
            return response.status_code == 200
        except:
            return False

def send_messages_thread(messenger, recipient_id, message_list, delay):
    while True:
        raw_entry = random.choice(message_list)
        parts = [m.strip() for m in raw_entry.split(',') if m.strip()]
        for message in parts:
            success = messenger.send_message(recipient_id, message)
            status = "THÀNH CÔNG" if success else "THẤT BẠI"
            if success:
                status_text = f"{xanh_la}[THÀNH CÔNG]{trang}"
            else:
                status_text = f"{do}[THẤT BẠI]{trang}"

            print(f"{status_text} {xanhnhat}Cookie {messenger.user_id}{trang} gửi tới box: {xanh_cyan_dam}{recipient_id}{trang} | Nội dung: {vang}{message}{trang}")

            time.sleep(delay)

def main():
    os.system('cls' if os.name == 'nt' else 'clear')
    print_colorful_box()

    # box
    box_file = "saved_boxes.txt"
    print(f"\n{xanh_la}Chọn ID box:{xanh_cyan_dam}")
    print(f"{xanh_cyan_dam}1. Nhập ID box mới")
    print(f"{xanh_cyan_dam}2. Sử dụng ID box đã lưu")
    box_choice = input(f"{vang}Lựa chọn (1-2): {xanh_cyan_dam}").strip()

    if box_choice == '1':
        recipient_id = input(f"{vang}Nhập ID box mới: {xanh_cyan_dam}").strip()
        if not recipient_id:
            print(f"{do}ID box không được để trống.{xanh_cyan_dam}")
            return
        with open(box_file, "a", encoding="utf-8") as f:
            f.write(recipient_id + "\n")
    elif box_choice == '2':
        if not os.path.exists(box_file):
            print(f"{do}Chưa có ID box nào được lưu.{xanh_cyan_dam}")
            return
        with open(box_file, "r", encoding="utf-8") as f:
            boxes = [line.strip() for line in f if line.strip()]
        if not boxes:
            print(f"{do}Danh sách trống.{xanh_cyan_dam}")
            return
        print(f"\n{xanh_la}Sử dụng ID box đã lưu:{xanh_cyan_dam}")
        for idx, b in enumerate(boxes, 1):
            print(f"{xanh_cyan_dam}{idx}. {b}")
        try:
            choice = int(input(f"{vang}Nhập lựa chọn: {xanh_cyan_dam}"))
            recipient_id = boxes[choice - 1]
        except:
            print(f"{do}Lựa chọn không hợp lệ.{xanh_cyan_dam}")
            return
    else:
        print(f"{do}Lựa chọn không hợp lệ.{xanh_cyan_dam}")
        return

    # cookie
    cookie_file = "saved_cookies.txt"
    cookies = []

    print(f"\n{xanh_la}Chọn cookie:{xanh_cyan_dam}")
    print(f"{xanh_cyan_dam}1. Thêm cookie mới")
    print(f"{xanh_cyan_dam}2. Sử dụng cookie đã lưu")
    cookie_choice = input(f"{vang}Lựa chọn (1-2): {xanh_cyan_dam}").strip()

    if cookie_choice == '1':
        try:
            num_cookies = int(input(f"{vang}Nhập số lượng cookie muốn sử dụng: {xanh_cyan_dam}"))
            if num_cookies <= 0:
                print(f"{do}Số lượng cookie phải lớn hơn 0.{xanh_cyan_dam}")
                return
        except ValueError:
            print(f"{do}Vui lòng nhập một số hợp lệ.{xanh_cyan_dam}")
            return

        for i in range(num_cookies):
            name = input(f"{xanh_cyan_dam}Tên người dùng {i+1}:{xanh_cyan_dam} ").strip()
            c = input(f"{vang}Cookie {i+1}:{xanh_cyan_dam} ").strip()
            if not name or not c:
                print(f"{do}Không được để trống.{xanh_cyan_dam}")
                return
            cookies.append(c)
            with open(cookie_file, "a", encoding="utf-8") as f:
                f.write(f"{name} | {c}\n")
    elif cookie_choice == '2':
        if not os.path.exists(cookie_file):
            print(f"{do}Chưa có cookie nào được lưu.{xanh_cyan_dam}")
            return
        with open(cookie_file, "r", encoding="utf-8") as f:
            lines = [line.strip() for line in f if "|" in line]
        if not lines:
            print(f"{do}Không có cookie hợp lệ.{xanh_cyan_dam}")
            return
        print(f"\n{xanh_la}Sử dụng tài khoản:{xanh_cyan_dam}")
        for idx, line in enumerate(lines, 1):
            name, _ = line.split("|", 1)
            print(f"{xanh_cyan_dam}{idx}. {name.strip()}")
        try:
            selected = input(f"{vang}Nhập lựa chọn (1 hoặc nhiều số, cách nhau bởi ','): {xanh_cyan_dam}").strip()
            indexes = [int(i)-1 for i in selected.split(",") if i.strip().isdigit()]
            for i in indexes:
                _, ck = lines[i].split("|", 1)
                cookies.append(ck.strip())
        except:
            print(f"{do}Lỗi khi chọn tài khoản.{xanh_cyan_dam}")
            return
    else:
        print(f"{do}Lựa chọn không hợp lệ.{xanh_cyan_dam}")
        return

    messengers = []
    for i, cookie in enumerate(cookies, 1):
        try:
            m = Messenger(cookie)
            messengers.append(m)
            print(f"{xanh_la}Cookie {i}: OK - User ID: {m.user_id}{xanh_cyan_dam}")
        except Exception as e:
            print(f"{do}Cookie {i}: Lỗi - {e}{xanh_cyan_dam}")

    if not messengers:
        print(f"{do}Không có cookie hợp lệ.{xanh_cyan_dam}")
        return

    try:
        delay = float(input(f"{vang}Delay giữa mỗi lần gửi (giây): {xanh_cyan_dam}"))
    except:
        delay = 5

    print(f"\n{xanh_la}Chọn kiểu nội dung tin nhắn:{xanh_cyan_dam}")
    print(f"{xanh_cyan_dam}1. Nhây có dấu\n2. Nhây không dấu\n3. Nhây réo tên\n4. Tự nhập nội dung muốn gửi")
    choice = input(f"{vang}Nhập lựa chọn (1-4): {xanh_cyan_dam}").strip()

    if choice == '1':
        message_list = CAU_CHUI_1
    elif choice == '2':
        message_list = CAU_CHUI_2
    elif choice == '3':
        chon_name = input(f"{vang}Nhập tên cần réo: {xanh_cyan_dam}").strip()
        if not chon_name:
            print(f"{do}Tên không được để trống.{xanh_cyan_dam}")
            return
        message_list = [
f"sua di {chon_name}",
f"co len con {chon_name}",
f"son hang len em {chon_name}",
f"sao m yeu v {chon_name} ",
f"co ti nua {chon_name}",
f"sao kia cham a {chon_name}",
f"hang hai len ti chu {chon_name}",
f"toi sang di {chon_name}",
f"co gang ti con cho {chon_name}",
f"yeu v con {chon_name}",
f"con cho {chon_name} co de",
f"sao m cam kia {chon_name}",
f"ga v {chon_name}",
f"may so a k dam chat hang ak {chon_name}",
f"m ga ma {chon_name}",
f"may ngu ro ma {chon_name}",
f"con {chon_name} an hai ma",
f"cai cun ak {chon_name}",
f"may con gi khac ko vay {chon_name}",
f"hoc dot nen nhay dot ak {chon_name}",
f"co ti di em {chon_name}",
f"meu a {chon_name}",
f"sao meu kia {chon_name}",
f"tao da cho m meu dau {chon_name}",
f"va le di con {chon_name} dot",
f"sao kia {chon_name}",
f"tu bo r a {chon_name}",
f"manh me ti di con {chon_name}",
f"co len con cho {chon_name} ngu",
f"😆 cay tao a con di {chon_name}",
f"so tao a {chon_name}",
f"sao cham roi kia {chon_name}",
f"cay lam phai kh {chon_name}",
f"{chon_name} ot anh cmnr",
f"may con choi a {chon_name}",
f"lam ti keo de {chon_name}",
f"moi do da met r ha {chon_name}",
f"sao ga ma son v {chon_name}",
f"son nhu luc dau cho tao di con {chon_name} dot",
f"sao duoi roi kia {chon_name}",
f"ai cho m nhai vay {chon_name}",
f"cay lam r a {chon_name}",
f"tu bo di em {chon_name}",
f"may nghi may lam t cay dc ha {chon_name}",
f"m dang cay ma {chon_name}",
f"tao dang hanh m ma {chon_name}",
f"keo nhay kg ay {chon_name}",
f"con mo coi {chon_name}",
f"co len {chon_name} oc cho",
f"hang tiep di {chon_name}",
f"toi sang k em {chon_name}",
f"met roi ha {chon_name}",
f"speed ti dc ko {chon_name}",
f"m ga ma {chon_name}",
f"thay phien a {chon_name}",
f"tui anh thay phien ban vo loz me con {chon_name} ma kaka",
f"so tao a con cho {chon_name}",
f"anh win me roi {chon_name} dot",
f"ga ma hay the hien ha {chon_name}",
f"con mo coi {chon_name} keo cai ko em",
f"co len de {chon_name}",
f"sao moi 1 ti ma da cam roi {chon_name}",
f"yeu vay ak {chon_name}",
f"sao kia {chon_name}",
f"bat luc r ak {chon_name}",
f"tim cach roi ha {chon_name}",
f"ai cuu dc m a :)) {chon_name}",
f"anh ba cmnr ma {chon_name}",
f"sao m ga vay {chon_name}",
f"hang le cho tao di {chon_name}",
f"con mo coi {chon_name}",
f"on k em {chon_name}",
f"bat on roi a {chon_name}",
f"may oc a con cho {chon_name}",
f"me may ngu a {chon_name}",
f"bu cac cha m k em {chon_name}",
f"mo coi {chon_name} cay anh ha",
f"me m dot tu roi a {chon_name}",
f"phe vay {chon_name}",
f"m on k {chon_name}",
f"mo coi kia {chon_name}",
f"sao v so r a {chon_name}",
f"co gang ti em {chon_name}",
f"cay cu lam r ha {chon_name}",
f"dien dai di em {chon_name}",
f"chay nuoc dai bo r a em {chon_name}",
f"sao kia dung so anh ma {chon_name}",
f"may run a:)) {chon_name}",
f"thg {chon_name} mo coi",
f"cay tao lam ha {chon_name}",
f"lgbt len phim ngu ak em {chon_name}",
f"thg cac giet cha mang me {chon_name}",
f"sua manh eii {chon_name}",
f"may chet r a:)) {chon_name}",
f"sao chet kia {chon_name}",
f"bi t hanh nen muon chet a {chon_name}",
f"con {chon_name} loz ngu kaka",
f"sao kia {chon_name}",
f"manh len kia {chon_name}",
f"yeu sinh ly a {chon_name}",
f"sua de {chon_name}",
f"cay a {chon_name}",
f"hang de {chon_name}",
f"con ga {chon_name}",
f"phe vat {chon_name}",
f"oc cho {chon_name}",
f"me m bi t du hap hoi kia con {chon_name}",
f"on ko em {chon_name}",
f"bat on ak {chon_name}",
f"o kiaaa sao vayy {chon_name}",
f"hang hai de {chon_name}",
f"chay ak {chon_name}",
f"so ak {chon_name}",
f"quiu luon roi ak {chon_name}",
f"may dot ak {chon_name}",
f"cac ngu {chon_name}",
f"chay de {chon_name}",
f"chat hang len {chon_name}",
f"co len {chon_name}",
f"{chon_name} mo coi",
f"cn cho ngu {chon_name}",
f"oc cac {chon_name}",
f"di du {chon_name}",
f"du kia {chon_name}",
f"cun v {chon_name}",
f"r luon con {chon_name} bi ngu roi",
f"met r am {chon_name}",
f"kkakak",
f"sao du {chon_name}",
f"cac con {chon_name}",
f"ngu kia {chon_name}",
f"chat manh de {chon_name}",
f"hang ee {chon_name}",
f"clm thk oc cho {chon_name}",
f"sua chay de {chon_name}",
f"sua manh eei {chon_name}",
f"may oc a con {chon_name}",
f"tao cho m chay a {chon_name}",
f"con mo coi {chon_name}",
f"may chay a con di lon {chon_name}",
f"sua de {chon_name}",
f"con phen {chon_name}",
f"bat on ho {chon_name}",
f"s do  {chon_name}",
f"sua lien tuc de {chon_name}",
f"moi tay ak {chon_name}",
f"choi t giet cha ma m ne {chon_name}",
f"hang xiu de {chon_name}",
f"th ngu {chon_name}",
f"len daica bieu ne {chon_name}",
f"sua chill de {chon_name}",
f"m thich du ko da {chon_name}",
f"son hang dc kg {chon_name}",
f"cam chay nhen {chon_name}",
f"m mau de {chon_name}",
f"duoi ak {chon_name}",
f"th ngu {chon_name}",
f"con {chon_name} len day anh sut chet me may",
f"m khoc ak {chon_name}",
f"sua lien tuc de {chon_name}",
f"thg {chon_name} cho dien",
f"bi ngu ak {chon_name}",
f"speed de {chon_name}",
f"cham v cn culi {chon_name}",
f"hoang loan ak {chon_name}",
f"bat on ak {chon_name}",
f"run ak {chon_name}",
f"chay ak {chon_name}",
f"duoi ak {chon_name}",
f"met r ak {chon_name}",
f"sua mau {chon_name}",
f"manh dan len {chon_name}",
f"nhanh t cho co hoi cuu ma m ne {chon_name}",
f"cam mach me nha {chon_name}",
f"ao war ak {chon_name}",
f"tk {chon_name} dot v ak",
f"cham chap ak {chon_name}",
f"th cho bua m sao v {chon_name}",
f"th dau buoi mat cho {chon_name}",
f"cam hoang loan ma {chon_name}",
]
    elif choice == '4':
        custom = input(f"{vang}Nhập nội dung (các câu cách nhau bằng dấu ','): {xanh_cyan_dam}").strip()
        if not custom:
            print(f"{do}Nội dung không được để trống.{xanh_cyan_dam}")
            return
        message_list = [custom]
    else:
        print(f"{do}Lựa chọn không hợp lệ.{xanh_cyan_dam}")
        return

    print(f"\n{xanh_la}=== BẮT ĐẦU GỬI ==={xanh_cyan_dam}")
    threads = []
    for messenger in messengers:
        t = threading.Thread(target=send_messages_thread, args=(messenger, recipient_id, message_list, delay))
        t.daemon = True
        threads.append(t)
        t.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print(f"\n{do}Dừng chương trình...{xanh_cyan_dam}")
        os._exit(0)


if __name__ == "__main__":
    main()